// AUTO-GENERATED by migration/scripts/build-content.mjs — do not edit by hand.
import type { AnyPage } from "@/lib/content-types";
import p0 from "./airport-taxi-luton.json";
import p1 from "./airport-taxi-biggin-hill.json";
import p2 from "./airport-taxi-southend.json";
import p3 from "./airport-taxi-london-city.json";
import p4 from "./chichester-taxi.json";
import p5 from "./lewes-taxi.json";
import p6 from "./stansted-taxi.json";
import p7 from "./heathrow-taxi.json";
import p8 from "./gatwick-taxi.json";
import p9 from "./horley-taxi.json";
import p10 from "./bognor-regis-taxi.json";
import p11 from "./littlehampton-taxi.json";
import p12 from "./midhurst-taxi.json";
import p13 from "./petworth-taxi.json";
import p14 from "./arundel-taxi.json";
import p15 from "./billingshurst-taxi.json";
import p16 from "./southwater-taxi.json";
import p17 from "./copthorne-taxi.json";
import p18 from "./horsham-taxi.json";
import p19 from "./worthing-taxi.json";
import p20 from "./steyning-taxi.json";
import p21 from "./henfield-taxi.json";
import p22 from "./ardingly-taxi.json";
import p23 from "./hassocks-taxi.json";
import p24 from "./haywards-heath-taxi.json";
import p25 from "./taxi-service-in-burgess-hill.json";
import p26 from "./taxi-service-in-east-grinstead.json";
import p27 from "./terms-conditions.json";
import p28 from "./home.json";

export const generatedPages: Record<string, AnyPage> = {
  "airport-taxi-luton": p0 as unknown as AnyPage,
  "airport-taxi-biggin-hill": p1 as unknown as AnyPage,
  "airport-taxi-southend": p2 as unknown as AnyPage,
  "airport-taxi-london-city": p3 as unknown as AnyPage,
  "chichester-taxi": p4 as unknown as AnyPage,
  "lewes-taxi": p5 as unknown as AnyPage,
  "stansted-taxi": p6 as unknown as AnyPage,
  "heathrow-taxi": p7 as unknown as AnyPage,
  "gatwick-taxi": p8 as unknown as AnyPage,
  "horley-taxi": p9 as unknown as AnyPage,
  "bognor-regis-taxi": p10 as unknown as AnyPage,
  "littlehampton-taxi": p11 as unknown as AnyPage,
  "midhurst-taxi": p12 as unknown as AnyPage,
  "petworth-taxi": p13 as unknown as AnyPage,
  "arundel-taxi": p14 as unknown as AnyPage,
  "billingshurst-taxi": p15 as unknown as AnyPage,
  "southwater-taxi": p16 as unknown as AnyPage,
  "copthorne-taxi": p17 as unknown as AnyPage,
  "horsham-taxi": p18 as unknown as AnyPage,
  "worthing-taxi": p19 as unknown as AnyPage,
  "steyning-taxi": p20 as unknown as AnyPage,
  "henfield-taxi": p21 as unknown as AnyPage,
  "ardingly-taxi": p22 as unknown as AnyPage,
  "hassocks-taxi": p23 as unknown as AnyPage,
  "haywards-heath-taxi": p24 as unknown as AnyPage,
  "taxi-service-in-burgess-hill": p25 as unknown as AnyPage,
  "taxi-service-in-east-grinstead": p26 as unknown as AnyPage,
  "terms-conditions": p27 as unknown as AnyPage,
  "home": p28 as unknown as AnyPage,
};
